language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction --no-progress"
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
  - '[ "${TRAVIS_PHP_VERSION:0:1}" == "5" ] && composer remove ely/php-code-style'
  - travis_retry composer update --no-interaction --prefer-source $PREFER_LOWEST
  - travis_retry phpenv rehash

stages:
  - Static Code Analysis
  - Test

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      script:
        - vendor/bin/php-cs-fixer fix -v --dry-run
  allow_failures:
    - php: nightly

script:
  - vendor/bin/phpunit
